pipeline:
  name: harness-community github app
  identifier: harnesscommunity_github_app
  projectIdentifier: setup
  orgIdentifier: Harness_Community
  tags: {}
  stages:
    - stage:
        name: auth
        identifier: auth
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: get token org
                  identifier: get_token_org
                  spec:
                    connectorRef: account.harnessImage
                    image: rssnyder/drone-github-app:latest
                    settings:
                      APP_ID: "314848"
                      INSTALLATION: "40515231"
                      PEM_B64: <+secrets.getValue("org.harness_solution_architecture_github_app_b64")>
                      JWT_FILE: jwt.txt
                      JWT_SECRET: harness_solution_architecture_github_app_jwt
                      JSON_FILE: output.json
                      JSON_SECRET: harness_solution_architecture_github_app_json
                      TOKEN_FILE: token.txt
                      TOKEN_SECRET: harnesscommunity_sa_app_token
                    envVariables:
                      HARNESS_ACCOUNT_ID: <+account.identifier>
                      HARNESS_PLATFORM_API_KEY: <+secrets.getValue("account.harness_platform_api_key")>
                      HARNESS_PLATFORM_ORGANIZATION: <+org.identifier>
              - step:
                  type: Run
                  name: list installations
                  identifier: list_installations
                  spec:
                    shell: Sh
                    command: |-
                      curl -s -L \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer <+secrets.getValue("org.harness_solution_architecture_github_app_jwt")>" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/app/installations
